on:
  push:
    tags:        
      - v*

name: Release

env:
  CARGO_TERM_COLOR: always
  RELEASE_ADDS: README.md LICENSE

jobs:
  build:
    name: Build treasure counter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build
        run: |
          cd treasure-counter
          npm install
          npm run build

      - name: Zip package
        run: 7z a -tzip -sdel treasure-counter.zip ./dist/treasure-counter

  release:
    needs: build
    name: Release package
    permissions:
      contents: write
    steps:
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "treasure-counter.zip"