on:
  push:
    tags:        
      - v*

name: Release

env:
  CARGO_TERM_COLOR: always
  RELEASE_ADDS: README.md LICENSE

jobs:
  build-release:
    name: Build and release package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          

      - name: Build treasure counter
        run: |
          cd treasure-counter
          npm install
          npm run build
          cd ..
          7z a -tzip -sdel treasure-counter.zip ./dist/treasure-counter

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "treasure-counter.zip"